commitment_amount_1 = ""
commitment_amount_2 = ""
gas_fee = ""
hashpath_1 = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
hashpath_2 = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
index_1 = ""
index_2 = ""
nullifier_1 = ""
nullifier_2 = ""
paymaster_fee = ""
refund_amount_1 = ""
refund_commitment_hash_1 = ""
refund_nullifier_1 = ""
refund_secret_1 = ""
root_1 = ""
root_2 = ""
secret_1 = ""
secret_2 = ""
token_address_1 = ""
token_address_2 = ""
